package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrderProductAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAllPropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertOrderProductAutoGeneratedPropertiesEquals(expected, actual);
        assertOrderProductAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAllUpdatablePropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertOrderProductUpdatableFieldsEquals(expected, actual);
        assertOrderProductUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductAutoGeneratedPropertiesEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(actual)
            .as("Verify OrderProduct auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductUpdatableFieldsEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(actual)
            .as("Verify OrderProduct relevant properties")
            .satisfies(a -> assertThat(a.getOrderQty()).as("check orderQty").isEqualTo(expected.getOrderQty()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrderProductUpdatableRelationshipsEquals(OrderProduct expected, OrderProduct actual) {
        assertThat(actual)
            .as("Verify OrderProduct relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
